### ISSUE TITLE
Corrupted output with backslash in .info files

### ISSUE THREAD

**Issue by raybellis** [Arakula/f9dasm#13]
This input in my `.info` file:

```
INSERT 0 \        OPT\        H03
```

produces this output:

```
        OT        H003
```

There are 8 spaces after each backslash.

**Comment by Arakula** [comment]
You don't need the second \\ ...
But I can't reproduce that oddity here. Which system and compiler are you using, and is that an ANSI (or UTF8 without BOM) file?

**Comment by raybellis** [comment]
I'm using clang 11.0.3 on macOS.

I get a similar issue with this:
```
INSERT 0xb56e \ FILL \$FF, \$D1BF - \*
```

producing this:
```
 FILL $F, $D1BBF - *
```

If I drop all of the backslashes except the first I get this:
```
 FILL FF, $D1BF  -
```

**Comment by Arakula** [comment]
As before,
`insert b56e \        FILL $FF, $D1BF - \*`
should be sufficient.
I'll look into what gcc / clang might do differently in this area - which is not much in most cases, as the logic looks like
`if (*q == '\\') strcpy(q, q + 1);`
Maybe that overlapping strcpy confuses clang.

**Comment by raybellis** [comment]
Ah, that would do it - `strcpy` of overlapping strings is "undefined behaviour" per the C standard.   For correct behaviour you'd need to do:
```
size_t n = strlen(q);
if (n > 0) {
  memmove(q + 1, q, n);
}
```

**Comment by raybellis** [comment]
or just:
```
  while (*(q + 1)) {
    *q = *(q + 1);
    ++q;
  }
```

**Comment by Arakula** [comment]
Something like the second one is what it's going to be.

**Comment by Arakula** [comment]
gcc and Microsoft have no problems with that construct, so I got by with it for all these years :-)

**Comment by raybellis** [comment]
You got lucky ;-)

**Comment by raybellis** [comment]
BTW, was it you that used my usim 6809 emulator many years ago to do some PPG Wave emulation?

**Comment by Arakula** [comment]
Yes, your usim (to be precise, the version used in Wolfgang Schwotzer's FlexEmu) was my starting point, but I'm using my own 6809 engine there since many years. Primarily because I needed an absolutely exact 6809 replica, which means identical cycle counts for all instructions and interrupts. At least the FlexEmu V2.00 version couldn't deliver that.

**Comment by raybellis** [comment]
It's a small world :)    I know of Rainer from various FB synth groups and GordonJCP too.   I also grew up in the same street as Paula Maddox who you may know of from the Monowave and various PPG-like wavetable systems.  We're still good friends now.

**Comment by Arakula** [comment]
Attached, find a [quick fix](https://github.com/Arakula/f9dasm/files/5050969/f9dasm.zip) at that should be "overlapping strcpy-free". Looks good here, whth gcc/Linux and MS-C/Windows. Please test it when your time permits.

And yes, I'm a Monowave owner :-) ... but unfortunately haven't had contact with Paula Maddox for quite some years now.

**Comment by raybellis** [comment]
That works fine, thanks :)    You can see Paula's latest stuff at https://dove-audio.com/
