### ISSUE TITLE
Example of a well-crafted info file?

### ISSUE THREAD

**Issue by phillipeaton** [Arakula/f9dasm#15]
I'm progressing with my first disassembly of a FLEX 6809 binary. 

Things are going well, but my info file is a bit of a mess, I don't really have a good picture in my head of what it should look like.

Does anyone have any good examples of well laid-out info files I could take a look at?

Thanks!

**Comment by Arakula** [comment]
I don't think there's such a thing ... all I can offer is a part of my PPG Wave information files. Might be a starting point for you, although that's strictly "the way _**I**_ did it". Not a general rule.

Here's an example, including binary and generating batch file:
[sample.zip](https://github.com/Arakula/f9dasm/files/5207638/sample.zip)

**Comment by phillipeaton** [comment]
Ah, this is exactly what I was hoping for, many thanks!

It showcases a bunch of functionality that I didn't really understand what
it was for, or how it works.

You could consider adding this into your repository as an example, it's
really useful to the newcomer.

**Comment by Arakula** [comment]
Considering :-)
