### ISSUE TITLE
"option -showzero" not working from nfo file

### ISSUE THREAD

**Issue by phillipeaton** [Arakula/f9dasm#19]
As subject. 

I'm assuming that this code should have `0` in front of the `,X` with the showzero option invoked.
```
        ROR     ,X                       *11E9: 66 84          'f.'
        LSRB                             *11EB: 54             'T'
        ROR     ,X                       *11EC: 66 84          'f.'
        LSRB                             *11EE: 54             'T'
        ROR     ,X                       *11EF: 66 84          'f.'
```
The start of my nfo file is 
```
*option noaddr
*option nohex
*option noasc
option cchar ; * Set comment character to ;
option flex    * Use standard FLEX labels
option noconv  * Convenience mnemonics
option forced  * Adds forced direct/extended markers < and >
option showzero * Doesn't seem to work
```
Does this look like a correct setting?

**Comment by Arakula** [comment]
Looks about right; I'll look into it on Sunday or Monday.
Seems this is only implemented for 6800 disassembly, not for 6809.

**Comment by phillipeaton** [comment]
Vielen dank!

BTW, I have mostly finished commenting the Sargon Chess FLEX binary I have, the nfo file is ~1,800 lines and the resultant asm file is ~2'900 lines. f9dasm has enabled me to make a really clean source code file and it also reassembles with only two long branch warnings using a09 - thanks for developing them both!

Soon I'll start adjusting the memory space to use the Vectrex ROM/RAM layout and combine it into a 6809 Forth environment so I can test individual subroutines and write a Forth test harness to make it play chess on the command line.

**Comment by Arakula** [comment]
Cool stuff! I guess taking apart and understanding the various chess algorithms wasn't exactly easy,

**Comment by phillipeaton** [comment]
> Cool stuff! I guess taking apart and understanding the various chess algorithms wasn't exactly easy,

Disclaimer: There is a version of Sargon that comes with the ReFLEX emulator and there was 6809 source code for it, except it's not the actual source, it's a very early version of the source, not coded by the guy who eventually did get it working, who was the ReFLEX author. 

He told me he spent a lot of time reworking/debugging it to make it work with the ReFLEX emulator, which has it's own video hardware emulation.

Unfortunately, he doesn't have the source code any longer, so, from his working program, I'm resurrecting the source for that working binary, together with the very early 6809 version of the source code, which has roughly the same layout for the engine subroutines, but with completely different UI code.

Additionally, I'm also referencing the Z80 source code that was published in the original Sargon book, it's a lot of cross-referencing between them, sometimes I wonder if it would be quicker to rewrite from scratch!

One other issue remains; it doesn't play the same as the Z80 TRS-80 Sargon implementation I'm using as a reference, but that's a problem for later.

Looking forward to the -showzero fix!

**Comment by Arakula** [comment]
After careful consideration, I won't do it. For the 6800, it makes sense; both instructions result in the same encoding `66 00`; omitting the zero is only a convenience there. But -

You see, for the 6809 (and at least for my A09; I haven't tested this on a 6809 machine with FLEX9 and the TSC assembler, but I seem to remember I did, many years ago), ` ROR ,X` and ` ROR 0,X` have the same effect, but are different instructions. The first is encoded as `66 84`, the second is encoded as `66 00`; forcing the zero might lead to code that, when re-assembled, creates a binary that isn't identical to the original. f9dasm knows the difference and disassembles them correctly, BTW.

I'll update the documentation for -showzero.

**Comment by phillipeaton** [comment]
Ah, I didn't know that, thanks for the learning. It wasn't a high priority one for me anyway, but might be nice to update the documentation of the flags that it's not available for 6809.
