### ISSUE TITLE
reading README.md?

### ISSUE THREAD

**Issue by SwissFrank** [Arakula/f9dasm#20]
I've gathered that .md means "markdown" format and that Visual Studio should be able to display this, though my Visual Studio 2017 doesn't.

Just "less" on the file of course is readable but there are HTML directives here and there.

I copied to README.html  and when opened with Chrome, I can now see the HTML as you intended, but the plain text is turned into a long paragraph.

I'm sure this is a super-newbie question but while I'm a senior/old-skool developer, I'm not up to date on things like this: how am I supposed to read this?!!?  I'm happy if it's a Linux shell tool to convert to troff to read with man, or just a Unix shell utility, or a browser, or Windows tool, or whatever....

Thanks in advance, I'm excited to get into a project tweaking a 6800 firmware.  I programmed 6502 30 years ago so it's probably as similar as Italian and Spanish :-D

**Comment by Arakula** [comment]
No idea. I only added a README.md because that's GitHub's mechanism of choice, and personally am not much of a fan of the markdown format.

But there's a f9dasm.htm as well that should be up to date and contains a HTML version of the documentation; Chrome should be perfectly happy with that

**Comment by Arakula** [comment]
AFAIR, the main difference between 6502 and 6800 is that 6800 is big-endian and 6502 is a little-endian machine. If you want to deal with both, you might try my [Disassembler Framework](https://github.com/Arakula/dasmfw/) instead of f9dasm. That one can handle 6502 as well.

**Comment by SwissFrank** [comment]
Sorry, just to be clear, I have experience with 6502, so I'm sure
reverse-engineering 6800 should be easy.  The opcodes and addressing modes
are similar.  My project is 6800-only.  Naturally your project compiles
fine on Fedora 31 and works on my dump.
